language: python
python:
  - "3.6"
  - "3.7"
  # - "3.8"

# Command to install dependencies
install:
  - pip install sympy strictyaml networkx

# Command to run tests
script:
  - pytest

deploy:
  provider: pypi
  user: "__token__"